kind: Kustomization
images:
- name: controller
  newName: ghcr.io/tektoncd/tekton-kueue
resources:
- deployment.yaml
- manifests.yaml
- service.yaml
- default-priority-class.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
- files:
  - config.yaml
  name: config
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/part-of: tekton-kueue
